# Uncomment this line to define a global platform for your project
 platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!


target ‘AMapSDK’ do
   pod 'AMap3DMap', '~> 4.5.0'
   pod 'AMapLocation', '~> 2.2.0'
   pod 'AMapNavi', '~> 2.3.0'
   pod 'AMapSearch', '~> 4.4.1'

end